method: grid  # or 'random' for random search
name: my-sweep
metric:
  goal: minimize
  name: coco/bbox_mAP

parameters:
  learning_rate:
    values: [1e-5, 5e-5, 1e-4]
  batch_size:
    values: [4, 8, 16]
  max_epochs:
    values: [50, 100]
