method: random
name: wj
metric:
  goal: minimize
  name: coco/bbox_mAP

parameters:
  learning_rate:
    min: 0.0001
    max: 0.01
  batch_size:
    values: [4, 8, 16]
  max_epochs:
    values: [50, 100]
